INSERT INTO `attractions` (`attraction_id`, `attraction_name`, `other_places_found`, `attraction_site_id`) VALUES
(1, 'elephant', 'Loitoktok Mount Elgon,Meru,Marsabit,Tsavo,Nanyuki,Ndaragwa,Mwingi,Mwea, Bisanadi Meru,Nasolot Kitale,Shimba,Narok', 1),
(2, 'hyrax', 'Loitoktok,Thika,Tsavo,Nanyuki,Mwea,Narok', 1),
(3, 'mongoose', 'Loitoktok,Thika,Tsavo,Nanyuki,Narok', 1),
(4, 'suni', 'Loitoktok', 1),
(5, 'duicker', 'Ndaragwa,Mount Elgon,Thika,Nanyuki,Kakamega,Shimba,Mwea,Narok,Kisumu,Nasolot Kitale', 1),
(6, 'bushbuck', 'Thika,Naivasha,Mount Elgon,Tsavo,Nanyuki,Nasolot Kitale,Kakamega,Shimba,Mwea,Kisumu', 1),
(7, 'waterbuck', 'Kisumu,Meru,Nakuru,Tsavo,Nanyuki,Nasolot Kitale,Shimba,Mwea', 1),
(8, 'leopard', 'Loitoktok,Ndaragwa,Nairobi,Naivasha,Meru,Nanyuki,Mwingi,Shimba,Mwea,Narok,Kisumu,Nairobi Safari', 1),
(9, 'bongo', 'Ndaragwa,Mount Elgon', 1),
(10, 'cheetah', 'Nairobi,Meru,Tsavo,Loitoktok,Bisanadi Meru,Narok,Nairobi Safari,Kisumu', 2),
(11, 'wild dog', 'Loitoktok', 2),
(12, 'buffalo', 'Naivasha,Nairobi,Homa Bay,Thika,Mount Elgon,Loitoktok,Meru,Nasolot Kitale,Bisanadi Meru,Shimba,Mwea,Nairobi', 2),
(13, 'giraffe', 'Homa Bay,Meru,Marsabit,Tsavo,Nairobi,Loitoktok,Shimba,Mwea,Narok,Kisumu', 2),
(14, 'zebra', 'Naivasha,Nairobi,Tsavo,Marsabit,Meru,Kisumu,Narok,Mwea,Nairobi Safari', 2),
(15, 'lion', 'Naivasha,Marsabit,Tsavo,Nairobi,Loitoktok,Mwingi,Nasolot Kitale,Bisanadi Meru,Narok,Kisumu,Nairobi,Nairobi Safari', 2),
(16, 'crocodile', 'Turkana,Kisumu,Tsavo,,Loitoktok,Mwea,Narok', 2),
(17, 'dik-dik', 'Thika,Marsabit,Tsavo,Loitoktok', 2),
(18, 'lesser kudu', 'Marsabit,Tsavo,Loitoktok,Nasolot Kitale,Mwea', 2),
(19, 'porcupine', 'Thika,Tsavo,Loitoktok,Narok', 2),
(20, 'hippo', 'Kisumu,Meru,Tsavo,Turkana,Mwingi,Nasolot Kitale,Narok,Mwea,Nairobi Safari', 3),
(21, 'bats', 'South Island Marsabit', 3),
(22, 'flamingo', 'Nakuru,Turkana,Yala', 3),
(23, 'fish', 'Kisumu,Garissa,Turkana', 3),
(24, 'swamp vegetation', 'Kitale', 4),
(25, 'lesser jacana', 'Kitale', 4),
(26, 'heron', 'Turkana,Kitale,Mwea', 4),
(27, 'duck', 'Kitale', 4),
(28, 'tortoise', 'Tsavo,Kitale,Narok,Kisumu,Kitale', 4),
(29, 'agama lizard', 'Homa Bay,Thika,Kisumu,Tsavo,Narok,Kitale', 4),
(30, 'cobra', 'Homa Bay,Meru,Turkana, Kitale', 4),
(31, 'chameleon', 'Narok, Kitale', 4),
(32, 'skull 1470, homo habilis', 'Sibiloi Lodwar', 5),
(33, 'koobi fora museum', 'Sibiloi Lodwar', 5),
(34, 'elephant Fossil', 'Sibiloi Lodwar', 5),
(35, 'tortoise Fossil', 'Sibiloi Lodwar', 5),
(36, 'ostrich', 'Kisumu,Nairobi', 5),
(37, 'bee-eater', 'Sibiloi Lodwar', 5),
(38, 'kori', 'Sibiloi Lodwar', 5),
(39, 'heuglin’s bustard', 'Sibiloi Lodwar', 5),
(40, 'carmine', 'Sibiloi Lodwar', 5),
(41, 'fox kestrel', 'Sibiloi Lowdar', 5),
(42, 'roan antelope', 'Homa Bay', 6),
(43, 'oribi antelope', 'Narok,Homa Bay', 6),
(44, 'velvet monkey', 'Thika,Homa Bay', 6),
(45, 'bohor reedbuck', 'Thika,Meru,Tsavo', 6),
(46, 'hartebeest', 'Meru,Naivasha,Homa Bay,Narok,Mwea', 6),
(47, 'puff adder', 'Kisumu,Meru,Tsavo,Turkana,Homa Bay,Homa Bay', 6),
(48, 'lizard', 'Kitale,Kisumu,Tsavo,Thika,Homa Bay,Shimba', 6),
(49, 'green mamba', 'Homa Bay', 6),
(50, 'skink', 'Homa Bay', 6),
(51, 'monkey', 'Kisumu,Ndaragwa,Thika,Nasolot Kitale,Kakamega,Shimba,Mwea,Narok,Kisumu,Nairobi,Nairobi Safari', 7),
(52, 'bushbaby', 'Thika', 7),
(53, 'squirrel', 'Mwea,Thika', 7),
(54, 'aardvark', 'Narok,Kisumu', 8),
(55, 'butterfly', 'Kisumu', 8),
(56, 'antelope', 'Mwingi,Shimba,Kisumu', 8),
(57, 'fish eagle', 'Kisumu', 8),
(58, 'hamerkop', 'Kendu Bay,Kisumu', 8),
(59, 'kingfisher', 'Kisumu', 8),
(60, 'gazelle', 'Naivasha,Nasolot Kitale,Narok,Longonot Naivasha', 9),
(61, 'bamboo', 'Mount Elgon', 10),
(62, 'podocapus', 'Mount Elgon', 10),
(63, 'tusker', 'Mount Elgon', 10),
(64, 'eland', 'Tsavo,Naivasha,Meru', 11),
(65, 'reedbuck', 'Homa Bay,Thika,Tsavo,Meru', 11),
(66, 'lake paradise', 'Marsabit', 12),
(67, 'wilderness', 'Garissa', 13),
(68, 'inselberg', 'Garissa', 13),
(69, 'river', 'Garissa', 13),
(70, 'rapid', 'Garissa', 13),
(71, 'hill', 'Nakuru,Chyulu Tsavo', 14),
(72, 'cave', 'Mount Elgon,Chyulu Tsavo', 14),
(73, 'beetle', 'Chyulu Tsavo', 14),
(74, 'tsetse fly', 'Chyulu Tsavo', 14),
(75, 'bat', 'Central Island Marsabit', 15),
(76, 'rhino', 'Homa Bay,Nakuru,Nairobi,Ndaragwa,Tsavo,Bisanadi Meru,Narok,Nairobi Safari', 16),
(77, 'gerenuck', 'Tsavo East', 18),
(78, 'hirola', 'Tsavo East', 18),
(79, 'canary', 'Yala,Hells Gate Naivasha', 21),
(80, 'cisticola', 'Yala,Hells Gate Naivasha', 21),
(81, 'warbler', 'Yala,Hells Gate Naivasha', 21),
(82, 'dik dik', 'Nasolot Kitale,Narok,Hells Gate Naivasha', 21),
(83, 'jackal', 'Nasolot Kitale,Mwea,Narok,Nairobi,Hells Gate Naivasha', 21),
(84, 'beisa oryx', 'Nasolot Kitale,Hells Gate Naivasha', 21),
(85, 'fringe-eared oryx', 'Nasolot Kitale,Hells Gate Naivasha', 21),
(86, 'snake', 'Kakamega,Hells Gate Naivasha', 21),
(87, 'potto', 'Kakamega,Hells Gate Naivasha', 21),
(88, 'bush pig', 'Kakamega,Shimba,Mwea,Hells Gate Naivasha', 21),
(89, 'clawless offer', 'Kakamega,Hells Gate Naivasha', 21),
(90, 'bee eater', 'Kakamega,Hells Gate Naivasha', 21),
(91, 'turaco', 'Kakamega,Hells Gate Naivasha', 21),
(92, 'turners eremomela', 'Kakamega,Hells Gate Naivasha', 21),
(93, 'parrot', 'Kakamega,Nairobi,Kisumu,Hells Gate Naivasha', 21),
(94, 'rhinocerous', 'Hells Gate Naivasha', 21),
(95, 'viper', 'Kakamega,Hells Gate Naivasha', 21),
(96, 'bird list', 'Narok,Hells Gate Naivasha', 21),
(97, 'fox', 'Narok,Hells Gate Naivasha', 21),
(98, 'monitor', 'Narok,Hells Gate Naivasha', 21),
(99, 'terrapin', 'Narok,Hells Gate Naivasha', 21),
(100, 'caracal', 'Narok,Hells Gate Naivasha', 21),
(101, 'hare', 'Narok,Hells Gate Naivasha', 21),
(102, 'topi', 'Narok,Hells Gate Naivasha', 21),
(103, 'starfish', 'Mombasa,Hells Gate Naivasha', 21),
(104, 'stone fish', 'Mombasa,Hells Gate Naivasha', 21),
(105, 'sea cucumber', 'Mombasa,Malindi,Hells Gate Naivasha', 21),
(106, 'coral', 'Mombasa,Malindi,Kwale,Hells Gate Naivasha', 21),
(107, 'turle', 'Mombasa,Hells Gate Naivasha', 21),
(108, 'crab plover', 'Mombasa,Kwale,Hells Gate Naivasha', 21),
(109, 'jellyfish', 'Mombasa,Malindi,Hells Gate Naivasha', 21),
(110, 'roseate tern', 'Mombasa,Kwale,Hells Gate Naivasha', 21),
(111, 'goose', 'Kendu Bay,Hells Gate Naivasha', 21),
(112, 'hadada ibis', 'Kendu Bay,Hells Gate Naivasha', 21),
(113, 'crested crane', 'Kendu Bay,Hells Gate Naivasha', 21),
(114, 'dove', 'Kendu Bay,Hells Gate Naivasha', 21),
(115, 'spur winged lover', 'Kendu Bay,Hells Gate Naivasha', 21),
(116, 'sacred ibis', 'Kendu Bay,Hells Gate Naivasha', 21),
(117, 'manikin', 'Kendu Bay,Hells Gate Naivasha', 21),
(118, 'hyena', 'Marsabit,Nairobi,Ndaragwa,Kisumu,Mwea,Shimba,Homa Bay,Nasolot Kitale,Narok', 6),
(119, 'impala', 'Kisumu,Naivasha,Homa Bay,Nasolot Kitale,Mwea,Narok', 6),
(120, 'black rhino', 'Nakuru,Tsavo,Nairobi,Nadaragwa', 6),
(121, 'white rhino', 'Ndaragwa,Nakuru,Tsavo,Nairobi', 6),
(122, 'cobra', 'Kitale,Meru,Turkana,Homa Bay,Kakamega,Shimba', 6),
(123, 'black mamba', 'Tsavo,Homa Bay', 6),
(124, 'gecko', 'Tsavo,Homa Bay', 6),
(125, 'baboon', 'Naivasha,Ndaragwa,Nairobi,Kisumu,Marsabit,Thika,Nasolot Kitale,Narok,Mwea', 7),
(126, 'pig', 'Meru,Tsavo,Thika', 7),
(127, 'reedbuck', 'Homa Bay,Meru,Tsavo,Thika', 7),
(128, 'warthog', 'Ndaragwa,Kisumu,Nairobi,Mwea', 8),
(129, 'gonolek', 'Yala,Kisumu', 8),
(130, 'forest', 'Kitale,Turkana,Marsabit,Mount Elgon', 10),
(131, 'cave', 'Tsavo,Mount Elgon', 10),
(132, 'waterfall', 'Ndaragwa,Garissa,Nakuru,Mount Elgon', 10),
(133, 'hill', 'Nakuru,Mount Elgon,Chyulu Tsavo', 14),
(134, 'hedge hog', 'Nanyuki,Kakamega,Tsavo,Chyulu Tsavo', 14),
(135, 'wildebeest', 'Narok,Nairobi', 19),
(136, 'serval cat', 'Shimba,Mwea,Narok,Nairobi,Kisumu, Ndaragwa', 20),
(137, 'genet cat', 'Mwea, Ndaragwa', 20),
(138, 'civet cat', 'Narok, Ndaragwa', 20),
(139, 'Sokoke cat', 'Nairobi,Ndaragwa', 20),
(140, 'genet', 'Shimba,Hells Gate Naivasha,', 21),
(141, 'bush baby', 'Shimba,Hells Gate Naivasha', 21),
(142, 'colombus', 'Shimba,Hells Gate Naivasha', 21),
(143, 'galago', 'Shimba,Hells Gate Naivasha', 21),
(144, 'shrew', 'Shimba,Hells Gate Naivasha', 21),
(145, 'eagle', 'Shimba,Hells Gate Naivasha,', 21),
(146, 'honey guide', 'Shimba,Hells Gate Naivasha', 21),
(147, 'falcon', 'Shimba,Hells Gate Naivasha', 21),
(148, 'cuckoo', 'Shimba,Hells Gate Naivasha', 21),
(149, 'guinea fowl', 'Shimba,Hells Gate Naivasha', 21),
(150, 'hornbill', 'Shimba,Hells Gate Naivasha', 21),
(151, 'quail', 'Shimba,Hells Gate Naivasha', 21),
(152, 'sunbird', 'Shimba,Hells Gate Naivasha', 21),
(153, 'ulugulu', 'Shimba,Hells Gate Naivasha', 21),
(154, 'fishing owl', 'Mwea,Hells Gate Naivasha', 21),
(155, 'sea turtle', 'Lamu,Kwale,Hells Gate Naivasha', 21),
(156, 'ridley', 'Lamu,Hells Gate Naivasha', 21),
(157, 'leatherback', 'Lamu,Hells Gate Naivasha', 21),
(158, 'reef fish', 'Lamu,Hells Gate Naivasha', 21),
(159, 'lobster', 'Lamu,Hells Gate Naivasha', 21),
(160, 'sea urchin', 'Lamu,Mombasa,Malindi,Hells Gate Naivasha', 21),
(161, 'sea star', 'Lamu,Malindi,Hells Gate Naivasha', 21),
(162, 'crab', 'Lamu,Mombasa,Malindi,Hells Gate Naivasha', 21),
(163, 'dolphin', 'Kwale,Hells Gate Naivasha', 21),
(164, 'whale', 'Kwale,Hells Gate Naivasha', 21),
(165, 'gastropod', 'Kwale,Hells Gate Naivasha', 21),
(166, 'grebe', 'Yala,Hells Gate Naivasha', 21),
(167, 'egret', 'Yala,Kendu Bay,Hells Gate Naivasha', 21),
(168, 'albizia', 'Kisumu,Hells Gate Naivasha', 21),
(169, 'fischer love birds', 'Kisumu,Hells Gate Naivasha', 21),
(170, 'crowned crane', 'Nairobi,Hells Gate Naivasha', 21);
